# Generated by Django 4.0.6 on 2022-07-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_city_id_alter_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ManyToManyField(to='maps.country'),
        ),
    ]
