# Generated by Django 4.0.6 on 2022-07-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_subject_remove_entry_authors_remove_entry_blog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='country',
        ),
        migrations.AddField(
            model_name='subject',
            name='university',
            field=models.ManyToManyField(to='maps.name'),
        ),
    ]
