# Generated by Django 4.0.6 on 2022-07-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_remove_name_tagline_remove_subject_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='university',
        ),
        migrations.AddField(
            model_name='subject',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.AddField(
            model_name='university',
            name='subject',
            field=models.ManyToManyField(to='maps.subject'),
        ),
    ]
