# Generated by Django 4.0.6 on 2022-08-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_university_remove_subject_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='pic',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
